language: python
python:
- '2.7'
env:
  global:
  - SECRET_KEY=blahblahblah
install:
- pip install -r requirements.txt
- pip install -r test_requirements.txt
before_script:
  - python manage.py collectstatic --noinput
script: coverage run manage.py test -v3
after_success: coveralls
notifications:
  email: false